baseURL = "https://its.justhelmi.com/"
languageCode = "en-us"
title = "it's just me"
googleAnalytics = "UA-73862641-2"

[params]
  author = "Helmi"
  info = "Web and App Developer"
  description = "Helmi's personal website"
  keywords = "blog,developer,personal"

[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/argubihelmi/"
[[params.social]]
  name = "LinkedIn"
  weight = 2
  url = "https://www.linkedin.com/in/argubihelmi/"
  
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "#"
[[menu.main]]
  name = "About"
  weight = 2
  url = "#"